import Product1 from '../../assets/product/watch.jpg'
const newArrivalsProduct = [
    {
        id: 0,
        productname: "alu",
        productprice: "50",
        productimage: Product1,
        isnew: "false",
        discount: "false",
        color: "yellow",
        stock: 150,
    },
    {
        id: 1,
        productname: "t-shirt",
        productprice: "350",
        productimage: Product1,
        isnew: "false",
        discount: "15",
        color: "red",
        stock: 0,
    },
    {
        id: 2,
        productname: "watch",
        productprice: "1580",
        productimage: Product1,
        isnew: "true",
        discount: "false",
        color: "false",
        stock: 12,
    },
    {
        id: 3,
        productname: "Monitor",
        productprice: "10500",
        productimage: Product1,
        isnew: "true",
        discount: "false",
        color: "white",
        stock: 17,
    },
    {
        id: 4,
        productname: "keyboard",
        productprice: "420",
        productimage: Product1,
        isnew: "false",
        discount: "20",
        color: "black",
        stock: 52,
    },
    {
        id: 5,
        productname: "Mouse",
        productprice: "650",
        productimage: Product1,
        isnew: "false",
        discount: "10",
        color: "red",
        stock: 0,
    },
    
  ]

  export default newArrivalsProduct